[package]
name = "cosmic-applet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic = { package = "libcosmic", git = "https://github.com/pop-os/libcosmic/", rev = "f06a81c", default-features = false, features = ["wayland", "tokio"] }
ron = { version = "0.8" }
serde = { version = "1.0" }
cosmic-panel-config = {git = "https://github.com/pop-os/cosmic-panel", rev = "adbe256" }
